add xenial-openjdk-7 flavor
Add an openjdk-7 backport flavor to new ubuntu LTS release. Android
5.x/6.x depends on openjdk-7.

Note you may meet a lot clang linker errors:

  error: unsupported reloc 42 # or 43

Check
https://android-review.googlesource.com/#/c/223100/1/core/clang/HOST_x86_common.mk
for a viable work-around.